NOP 		= 0x00    	#
SWRESET 	= 0x01		# Software Reset
RDDID 		= 0x04		# Read Display ID
RDDST 		= 0x09		# Read Display Status
RDDPM 		= 0x0A		# Read Display Power Mode
RDDMADCTL	= 0x0B		# Read Display MADCTL
RDDCOLMOD	= 0x0C		# Read Display Pixel Format
RDDIM 		= 0x0D		# Read Display Image Mode
RDDSM 		= 0x0E		# Read Display Signal Mode
RDDSDR 		= 0x0F		# Read Display Self-Diagnostic Result
SLPIN 		= 0x10		# Sleep In
SLPOUT 		= 0x11		# Sleep Out
PTLON 		= 0x12		# Partial Display Mode On
NORON 		= 0x13		# Normal Display Mode On
INVOFF 		= 0x20		# Display Inversion Off
INVON 		= 0x21		# Display Inversion On
GAMSET 		= 0x26		# Gamma Set
DISPOFF		= 0x28		# Display Off
DISPON 		= 0x29		# Display On
CASET 		= 0x2A		# Column Address Set
RASET 		= 0x2B		# Row Address Set
RAMWR 		= 0x2C		# Memory Write
RGBSET 		= 0x2D		# Color Setting for 4K, 65K and 262K
RAMRD 		= 0x2E		# Memory Read
PTLAR 		= 0x30		# Partial Area
SCRLAR 		= 0x33		# Scroll Area Set
TEOFF 		= 0x34		# Tearing Effect Line OFF
TEON 		= 0x35		# Tearing Effect Line ON
MADCTL 		= 0x36		# Memory Data Access Control
VSCSAD 		= 0x37		# Vertical Scroll Start Address of RAM
IDMOFF 		= 0x38		# Idle Mode Off
IDMON 		= 0x39		# Idle Mode On
COLMOD 		= 0x3A		# Interface Pixel Format
RDID1 		= 0xDA		# Read ID1 Value
RDID2	 	= 0xDB      # Read ID2 Value
RDID3	 	= 0xDC      # Read ID3 Value
FRMCTR1	 	= 0xB1      # Frame Rate Control (In normal mode/ Full colors)
FRMCTR2	 	= 0xB2      # Frame Rate Control (In Idle mode/ 8-colors)
FRMCTR3	 	= 0xB3      # Frame Rate Control (In Partial mode/ full colors)
INVCTR	 	= 0xB4      # Display Inversion Control
PWCTR1	 	= 0xC0      # Power Control 1
PWCTR2	 	= 0xC1      # Power Control 2
PWCTR3	 	= 0xC2      # Power Control 3 (in Normal mode/ Full colors)
PWCTR4	 	= 0xC3      # Power Control 4 (in Idle mode/ 8-colors)
PWCTR5	 	= 0xC4      # Power Control 5 (in Partial mode/ full-colors)
VMCTR1	 	= 0xC5      # VCOM Control 1
VMOFCTR	 	= 0xC7      # VCOM Offset Control
WRID2	 	= 0xD1      # Write ID2 Value
WRID3	 	= 0xD2      # Write ID3 Value
NVFCTR1	 	= 0xD9      # NVM Control Status
NVFCTR2	 	= 0xDE      # NVM Read Command
NVFCTR3	 	= 0xDF      # NVM Write Command
GMCTRP1	 	= 0xE0      # Gamma ('+' polarity) Correction Characteristics Setting
GMCTRN1	 	= 0xE1      # Gamma ('-' polarity) Correction Characteristics Setting
GCV			= 0xFC      # Gate Pump Clock Frequency Variable
